version: '3.1'

services:
  backend:
    build: ./backend
    image: backend
    container_name: backend 
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata:
